export const CREATE_BILLS = 'CREATE_BILLS'
export const CREATE_DATAREQUEST_BILLS = 'CREATE_DATAREQUEST_BILLS'
export const CREATE_DATASUCCESS_BILLS = 'CREATE_DATASUCCESS_BILLS'
export const CREATE_DATAERROR_BILLS = 'CREATE_DATAERROR_BILLS'
