export const CREATE_PAYBILL = 'CREATE_PAYBILL'
export const CREATE_DATAREQUEST_PAYBILL = 'CREATE_DATAREQUEST_PAYBILL'
export const CREATE_DATASUCCESS_PAYBILL = 'CREATE_DATASUCCESS_PAYBILL'
export const CREATE_DATAERROR_PAYBILL = 'CREATE_DATAERROR_PAYBILL'
