export const SEARCH_PENDINGBILLS = 'SEARCH_PENDINGBILLS'
export const SEARCH_DATAREQUEST_PENDINGBILLS = 'SEARCH_DATAREQUEST_PENDINGBILLS'
export const SEARCH_DATASUCCESS_PENDINGBILLS = 'SEARCH_DATASUCCESS_PENDINGBILLS'
export const SEARCH_DATAERROR_PENDINGBILLS = 'SEARCH_DATAERROR_PENDINGBILLS'
