export const SEARCH_PAYMENTS = 'SEARCH_PAYMENTS'
export const SEARCH_DATAREQUEST_PAYMENTS = 'SEARCH_DATAREQUEST_PAYMENTS'
export const SEARCH_DATASUCCESS_PAYMENTS = 'SEARCH_DATASUCCESS_PAYMENTS'
export const SEARCH_DATAERROR_PAYMENTS = 'SEARCH_DATAERROR_PAYMENTS'
